# Starter pipeline


trigger:
- name

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@1
  displayName: "Terraform Installation"
  inputs:
    terraformVersion: '1.6.6'

- task: TerraformTask@5
  displayName: "terraform init"
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Automating'
    backendAzureRmResourceGroupName: 'Test_RG_Storage'
    backendAzureRmStorageAccountName: 'automatingtfstorage'
    backendAzureRmContainerName: 'container1'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  displayName: "terraform validate"
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTask@5
  displayName: "terraform plan"
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Automating'

- task: TerraformTask@5
  displayName: "terraform apply"
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Automating'
